all:
	mv attacker_server.py attacker_server
	mv crack_attack.py crack_attack
	chmod +x attacker_server
	chmod +x crack_attack
clean:
	rm -rf zipped_cat zipped_cat.h zipped_cat.zip cat cat_backup address_port.h address_port.txt connection.h
	mv attacker_server attacker_server.py
	mv crack_attack crack_attack.py
